### ISSUE TITLE
Not able to acces from admin

### ISSUE THREAD

**Issue by MichielTG** [Nabooru/module-address-validation-core#8]
We would like to test the module however, for some reason we are unable to configure the extension.

We have uploaded the extension to App/Code folder
Enabled the extension
And setup:upgrade
 
I'm looking forward if somebody know how to configure the extension.

Regards,

Michiel

**Comment by johmanx10** [comment]
Hello there @MichielTG,

First of all, this extension is built with Magento 2 in mind. It is built to be installed through composer.
At the time of writing this, the extension is in an alpha state. Not all required functionality it present.

Secondly, this specific [package](https://getcomposer.org/doc/05-repositories.md#package) is merely the core package, which enabled specific implementation packages to introduce adapters for address lookups and validation. See the [PCA Predict adapter](https://github.com/Nabooru/module-address-validation-adapter-pcapredict) and the [Dummy adapter](https://github.com/Nabooru/module-address-validation-adapter-dummy) for more information.

Thirdly, you will find that, rather unconventionally, this extension has no own configuration panel in the Magento backend. It tries to be rather unintrusive and merges it's configuration with existing Magento configuration. In [system.xml](https://github.com/Nabooru/module-address-validation-core/blob/master/etc/adminhtml/system.xml) you can see that the configuration merges with the checkout configuration and therefore lives somewhere under the sales section of configuration.

I would gladly invite you to help finish the corresponding extensions. Currently, with the implementation of the dummy adapter, all backend configuration AND the controller for validation and lookups are written. The only part that needs to be added to make this fully functional, is the front-end code to hook into the checkout templates.
